---
abstract: 'pure perl implementation of MongoDB protocol'
author:
  - 'Yury Zavarin <yury.zavarin@gmail.com>'
build_requires:
  Test::Class: 0
  Test::More: 0
  parent: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MongoDBx-Protocol
requires:
  BSON: 0
  Bit::Vector: 0
  Carp: 0
  Params::Validate: 0
  perl: v5.8.5
  strict: 0
  warnings: 0
resources:
  homepage: http://github.com/tadam/MongoDBx-Protocol
  repository: git://github.com/tadam/MongoDBx-Protocol.git
version: 0.01
